FROM node:20.8.1 AS build
WORKDIR /

COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS serve
COPY --from=build /build /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"] 
